### ISSUE TITLE
SWTBotTests fail randomly on CI

### ISSUE THREAD

**Issue by lbeurerkellner** [ConsistAnts/ConsistAnts#5]
There seems to be a timing issue with cleaning up workspace projects in our SwtBot tests.

They fail randomly in some builds (e.g. https://travis-ci.org/ConsistAnts/ConsistAnts/builds/310566776).

**Comment by clauslor** [comment]
_Running de.hu_berlin.cchecker.ui.tests.RunAsSRELearningSwtBotTest
 Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 7.342 sec <<< FAILURE! - in de.hu_berlin.cchecker.ui.tests.RunAsSRELearningSwtBotTest_
testRunLearnModel(de.hu_berlin.cchecker.ui.tests.RunAsSRELearningSwtBotTest)  Time elapsed: 5.276 sec  <<< ERROR!
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Timed out waiting for tree item tracedataset_task1.trc
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:522)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:496)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:484)
	at org.eclipse.swtbot.swt.finder.widgets.SWTBotTreeItem.getTreeItem(SWTBotTreeItem.java:863)
	at org.eclipse.swtbot.swt.finder.widgets.SWTBotTreeItem.select(SWTBotTreeItem.java:561)
	at org.eclipse.swtbot.swt.finder.widgets.SWTBotTreeItem.select(SWTBotTreeItem.java:611)
	at de.hu_berlin.cchecker.ui.tests.RunAsSRELearningSwtBotTest.testRunLearnModel(RunAsSRELearningSwtBotTest.java:57)

Running de.hu_berlin.cchecker.ui.tests.RunAsPALearningSwtBotTest

(Eclipse:20929): Gtk-WARNING **: Negative content width -6 (allocation 1, extents 4x3) while allocating gadget (node toolbar, owner GtkToolbar)

(Eclipse:20929): Gtk-WARNING **: Negative content width -6 (allocation 1, extents 4x3) while allocating gadget (node toolbar, owner GtkToolbar)
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.786 sec - in de.hu_berlin.cchecker.ui.tests.RunAsPALearningSwtBotTest
testRunLearnModel(de.hu_berlin.cchecker.ui.tests.RunAsPALearningSwtBotTest)  Time elapsed: 2.129 sec
Running de.hu_berlin.cchecker.ui.tests.RunAsSRETransformationSwtBotTest

(Eclipse:20929): Gtk-WARNING **: Negative content width -6 (allocation 1, extents 4x3) while allocating gadget (node toolbar, owner GtkToolbar)

(Eclipse:20929): Gtk-WARNING **: Negative content width -6 (allocation 1, extents 4x3) while allocating gadget (node toolbar, owner GtkToolbar)
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.839 sec - in de.hu_berlin.cchecker.ui.tests.RunAsSRETransformationSwtBotTest
testRunTransformSREToPA(de.hu_berlin.cchecker.ui.tests.RunAsSRETransformationSwtBotTest)  Time elapsed: 1.561 sec

Results :

Tests in error: 
  RunAsSRELearningSwtBotTest.testRunLearnModel:57 » WidgetNotFound Timed out wai...

Tests run: 6, Failures: 0, Errors: 1, Skipped: 0

1   0x7efe5b4a5e37 /usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-4.0.so.18(WTFCrash+0x17) [0x7efe5b4a5e37]
2   0x7efe5c3ccb06 /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37(+0x603b06) [0x7efe5c3ccb06]
3   0x7efe5c4114da /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37(+0x6484da) [0x7efe5c4114da]
4   0x7efe5c411929 /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37(+0x648929) [0x7efe5c411929]
5   0x7efe5c5ce442 /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37(+0x805442) [0x7efe5c5ce442]
6   0x7efe860c392a /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_unref+0x19a) [0x7efe860c392a]
7   0x7eff087e2270 /lib/x86_64-linux-gnu/libc.so.6(+0x3a270) [0x7eff087e2270]
8   0x7eff087e22ca /lib/x86_64-linux-gnu/libc.so.6(+0x3a2ca) [0x7eff087e22ca]
9   0x7eff07e3e8f7 /opt/jdk1.8.0_152/jre/lib/amd64/server/libjvm.so(+0x6928f7) [0x7eff07e3e8f7]
10  0x7eff08284bb5 /opt/jdk1.8.0_152/jre/lib/amd64/server/libjvm.so(+0xad8bb5) [0x7eff08284bb5]
11  0x7eff08282f7a /opt/jdk1.8.0_152/jre/lib/amd64/server/libjvm.so(+0xad6f7a) [0x7eff08282f7a]
12  0x7eff082832fe /opt/jdk1.8.0_152/jre/lib/amd64/server/libjvm.so(+0xad72fe) [0x7eff082832fe]
13  0x7eff08283770 /opt/jdk1.8.0_152/jre/lib/amd64/server/libjvm.so(+0xad7770) [0x7eff08283770]
14  0x7eff080d98d8 /opt/jdk1.8.0_152/jre/lib/amd64/server/libjvm.so(+0x92d8d8) [0x7eff080d98d8]
15  0x7eff08f906da /lib/x86_64-linux-gnu/libpthread.so.0(+0x76da) [0x7eff08f906da]
16  0x7eff088b0d7f /lib/x86_64-linux-gnu/libc.so.6(clone+0x5f) [0x7eff088b0d7f]

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007efe5b4a5e3c, pid=20929, tid=0x00007efeeca57700

 JRE version: Java(TM) SE Runtime Environment (8.0_152-b16) (build 1.8.0_152-b16)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.152-b16 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 C  [libjavascriptcoregtk-4.0.so.18+0xd0fe3c]  WTFCrash+0x1c
